/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
       // Initialize your test class
        ImdbRating test = new ImdbRating();

        //TODO: call your test case functions one after other here
        test.imdbRating();

        //END Tests
        test.endTest();

        // End your test by clearing connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
